00:51:17 - INFO - Попытка войти}
00:51:17 - INFO - У Вас есть 3 попытки}
00:51:22 - WARNING - Вы ввели пустой пароль.}
00:51:22 - WARNING - Вы ввели пустой пароль.}
00:51:22 - ERROR - Войти не удалось, пароль неверный}
00:51:28 - INFO - Попытка войти}
00:51:28 - INFO - У Вас есть 3 попытки}
00:51:30 - WARNING - Вы ввели пустой пароль.}
00:51:30 - ERROR - Войти не удалось, пароль неверный}
00:52:53 - INFO - Попытка войти}
00:52:53 - INFO - У Вас есть 3 попытки}
00:53:04 - INFO - Попытка войти
00:53:04 - INFO - У Вас есть 3 попытки
00:53:09 - WARNING - Вы ввели пустой пароль.
00:53:11 - WARNING - Вы ввели пустой пароль.
00:53:11 - ERROR - Войти не удалось, пароль неверный
00:53:27 - INFO - Попытка войти
00:53:27 - INFO - У Вас есть 3 попытки.
00:53:29 - ERROR - Вы ввели некорректный символ: 
Traceback (most recent call last):
  File "/Users/macintosh/Documents/Программирование/Python/SkillBox/Python Advanced/mod6/authentication.py", line 22, in input_and_check_password
    hasher.update(password.encode("latin-1"))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-2: ordinal not in range(256)
01:26:24 - INFO - Попытка войти
01:26:24 - INFO - У Вас есть 3 попытки.
01:26:42 - INFO - Попытка войти
01:26:42 - INFO - У Вас есть 3 попытки.
01:27:21 - INFO - Попытка войти
01:27:21 - INFO - У Вас есть 3 попытки.
01:27:50 - INFO - Попытка войти
01:27:50 - INFO - У Вас есть 3 попытки.
01:28:20 - INFO - Попытка войти
01:28:20 - INFO - У Вас есть 3 попытки.
01:34:29 - INFO - Попытка войти
01:34:29 - INFO - У Вас есть 3 попытки.
01:36:08 - INFO - Попытка войти
01:36:08 - INFO - У Вас есть 3 попытки.
01:38:54 - INFO - Попытка войти
01:38:54 - INFO - У Вас есть 3 попытки.
01:39:13 - INFO - Попытка войти
01:39:13 - INFO - У Вас есть 3 попытки.
01:45:29 - INFO - Попытка войти
01:45:29 - INFO - У Вас есть 3 попытки.
01:47:26 - INFO - Попытка войти
01:47:26 - INFO - У Вас есть 3 попытки.
01:47:40 - INFO - Попытка войти
01:47:40 - INFO - У Вас есть 3 попытки.
01:47:47 - INFO - Попытка войти
01:47:47 - INFO - У Вас есть 3 попытки.
01:49:06 - INFO - Попытка войти
01:49:06 - INFO - У Вас есть 3 попытки.
01:50:19 - INFO - Попытка войти
01:50:19 - INFO - У Вас есть 3 попытки.
01:50:47 - INFO - Попытка войти
01:50:47 - INFO - У Вас есть 3 попытки.
01:51:42 - INFO - Попытка войти
01:51:42 - INFO - У Вас есть 3 попытки.
01:51:52 - INFO - Попытка войти
01:51:52 - INFO - У Вас есть 3 попытки.
01:52:06 - INFO - Попытка войти
01:52:06 - INFO - У Вас есть 3 попытки.
01:52:11 - INFO - Попытка войти
01:52:11 - INFO - У Вас есть 3 попытки.
01:52:13 - INFO - Попытка войти
01:52:13 - INFO - У Вас есть 3 попытки.
01:52:22 - INFO - Попытка войти
01:52:22 - INFO - У Вас есть 3 попытки.
01:52:42 - INFO - Попытка войти
01:52:42 - INFO - У Вас есть 3 попытки.
01:53:20 - INFO - Попытка войти
01:53:20 - INFO - У Вас есть 3 попытки.
01:53:30 - INFO - Попытка войти
01:53:30 - INFO - У Вас есть 3 попытки.
01:54:08 - INFO - Попытка войти
01:54:08 - INFO - У Вас есть 3 попытки.
01:54:24 - INFO - Попытка войти
01:54:24 - INFO - У Вас есть 3 попытки.
01:54:30 - INFO - Попытка войти
01:54:30 - INFO - У Вас есть 3 попытки.
01:54:42 - INFO - Попытка войти
01:54:42 - INFO - У Вас есть 3 попытки.
01:54:48 - INFO - Попытка войти
01:54:48 - INFO - У Вас есть 3 попытки.
01:54:58 - INFO - Попытка войти
01:54:58 - INFO - У Вас есть 3 попытки.
01:55:02 - INFO - Попытка войти
01:55:02 - INFO - У Вас есть 3 попытки.
01:58:23 - INFO - Попытка войти
01:58:23 - INFO - У Вас есть 3 попытки.
01:58:28 - ERROR - Некорректный символ: 
Traceback (most recent call last):
  File "/Users/macintosh/Documents/Программирование/Python/SkillBox/Python Advanced/mod6/authentication.py", line 45, in input_and_check_password
    hasher.update(password.encode("latin-1"))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-3: ordinal not in range(256)
01:58:38 - WARNING - Содержит слово
01:58:53 - ERROR - Войти не удалось, пароль неверный
